In [66]:
import pandas as pd
import json
# x = {"a": {"a1": 1, "a2":2}, "b": {"a1": 3, "a2": 4}}
with open (r"C:\Users\micha\Downloads\Bens_Tetris_Regression\regression_data.json", "r") as f:
    x = json.load(f)
    
x = {key: {**{k:val[k] for k in val if k != "metrics"}, **val["metrics"]} for key, val in x.items() }
x = {key: {**{k:val[k] for k in val if k != "params"}, **{p_name: p_val for p_val, p_name in zip(val["params"], ['a', 'b', 'c'])}} for key, val in x.items() }

df = pd.DataFrame(x).T
df.index.name = "playername"
df = df.loc[df["gamesplayed"] > 200]
# df.drop(columns=['warnings'], inplace = True)
df

,timeplayed,gamesplayed,warnings,RMSE,a,b,c
playername,,,,,,,
0kaikami0,1543,8975,[],10.185037,-0.008967,4.012685,35.583115
0RIG1N,1218,4462,[],13.618136,-0.001714,4.388944,16.961164
1021839,1470,2567,[],16.946345,-0.012884,4.688726,43.866144
1081p,1282,374,[],7.414906,-0.005517,3.581151,27.017588
13pake,842,4838,[],19.758353,-0.002777,3.764453,42.72662
...,...,...,...,...,...,...,...
피로,278,234,[],4.618202,-0.141156,2.503753,33.898015
핵원펀맨,855,1054,[],21.660203,-0.000017,6.898225,-937.617131
핵펀맨,978,513,[],21.62211,-0.005861,1.420982,51.185475
화쯔,567,504,[],8.100043,-0.015594,3.464842,41.06151
황효중,1105,628,[],13.213153,0.000017,6.909529,-968.974472

In [ ]:
df.to_csv ('regression_data.csv', index = True, header=True)